# Libraries needed 
import random  # For generating random characters
import string  # For using predefined sets of letters, digits, and symbols

# Function to generate a password
def generate_password():
    """
    This function generates a random password based on user input.
    It allows the user to choose password length and whether to include symbols.
    """
    # User enters the length of password
    length = int(input("Enter password length: "))

    # If the length of password is 4 or less, a warning message will be printed
    if length <= 4:
        print("⚠️ Warning: Password length is very short and not secure.")

    # User chooses whether to include symbols in the password
    use_symbols = input("Include symbols? (y/n): ").lower()

    # Base characters for password: uppercase + lowercase letters and digits
    characters = string.ascii_letters + string.digits

    # Add symbols to the character set if user chose 'y'
    if use_symbols == 'y':
        characters += string.punctuation

    # Password is generated by randomly selecting characters from the set
    password = ''.join(random.choice(characters) for _ in range(length))

    # Print the generated password
    print("Generated password:", password)

# Main loop to allow multiple password generations
while True:
    generate_password()  # Call the password generator function

    # Ask user if they want to generate another password
    again = input("Generate another password? (y/n): ").lower()

    # If the user does not enter 'y', exit the loop and end program
    if again != 'y':
        print("Goodbye!")
        break
